# Answers of Exercise 1

# Exercise 1

Create a 2D tensor and then add a dimension of size 1 inserted at the 0th axis.

In [2]:
import torch
a = torch.rand(3,3)
a = a.unsqueeze(0)
print(a)
print(a.shape)

tensor([[[0.1025, 0.7147, 0.0799],
         [0.0816, 0.3718, 0.7391],
         [0.4600, 0.8501, 0.6052]]])
torch.Size([1, 3, 3])


# Exercise 2 

Remove the extra dimension you just added to the previous tensor.

In [3]:
a = a.squeeze(0)
print(a.shape)

torch.Size([3, 3])


# Exercise 3

Create a random tensor of shape 5x3 in the interval [3, 7)

In [4]:
3 + torch.rand(5, 3) * 4

tensor([[3.4159, 5.6724, 3.8796],
        [3.9895, 5.6875, 6.7015],
        [6.1025, 6.2243, 3.1327],
        [3.8927, 3.7360, 3.7333],
        [5.5081, 6.9481, 6.1389]])

# Exercise 4

Create a tensor with values from a normal distribution (mean=0, std=1).

In [5]:
a = torch.rand(3,3)
a.normal_(mean=0, std=1)

tensor([[-3.2413, -1.0959,  0.0255],
        [-0.7650, -0.7929, -0.8407],
        [ 0.0735,  1.2410,  1.8930]])

# Exercise 5

Retrieve the indexes of all the non zero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).

In [6]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

# Exercise 6

Create a random tensor of size (3,1) and then horizonally stack 4 copies together.

In [7]:
a = torch.rand(3,1)
a.expand(3,4)

tensor([[0.1384, 0.1384, 0.1384, 0.1384],
        [0.4065, 0.4065, 0.4065, 0.4065],
        [0.4903, 0.4903, 0.4903, 0.4903]])

# Exercise 7

Return the batch matrix-matrix product of two 3 dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [8]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a, b)

tensor([[[2.0554, 1.7474, 3.1289, 1.7918],
         [1.3558, 0.7265, 1.8754, 0.6584],
         [2.0602, 0.9311, 2.1633, 0.8085],
         [1.8815, 1.4596, 2.9856, 1.4597]],

        [[1.7473, 2.9274, 1.0696, 2.0732],
         [1.3459, 1.8406, 0.4827, 1.3264],
         [1.0649, 1.9077, 0.7305, 1.1068],
         [1.2528, 2.2711, 0.6393, 1.5071]],

        [[1.0615, 0.9192, 2.1972, 1.7012],
         [0.7621, 0.4631, 1.1517, 0.9299],
         [0.7012, 0.5184, 1.1954, 0.8318],
         [0.8308, 0.6948, 1.6619, 1.3858]]])

# Exercise 8

Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [9]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.6463, 0.6520, 1.1887, 1.3435],
         [0.8871, 0.4103, 0.8821, 1.0778],
         [0.5989, 0.2574, 0.5931, 0.6403],
         [1.2315, 0.7622, 0.9642, 0.6910]],

        [[1.3239, 0.5323, 1.0606, 1.1069],
         [0.7052, 0.5214, 0.8463, 0.4247],
         [1.1626, 0.5888, 0.8522, 1.0317],
         [1.2240, 0.7754, 1.0326, 1.1752]],

        [[0.6535, 0.3073, 0.4279, 0.5316],
         [1.5770, 0.7350, 1.3032, 1.3383],
         [0.8394, 0.3055, 0.7137, 0.5578],
         [1.2110, 0.6920, 1.0417, 1.1084]]])